name: Regression test - Coupons

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Configure Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            
            - name: Install dependecies
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            
            - name: Execute tests
              run: |
                source venv/bin/activate
                pytest --junitxml=reports/results.xml
            
            - name: Upload report test
              uses: action/upload-artifact@v3
              with:
                name: test-results
                path: reports/results.xml
                retention-days: 30
